lib: [
  "_build/install/default/lib/Character/META"
  "_build/install/default/lib/Character/character.a"
  "_build/install/default/lib/Character/character.cma"
  "_build/install/default/lib/Character/character.cmi"
  "_build/install/default/lib/Character/character.cmt"
  "_build/install/default/lib/Character/character.cmti"
  "_build/install/default/lib/Character/character.cmx"
  "_build/install/default/lib/Character/character.cmxa"
  "_build/install/default/lib/Character/character.ml"
  "_build/install/default/lib/Character/character.mli"
  "_build/install/default/lib/Character/character__.cmi"
  "_build/install/default/lib/Character/character__.cmt"
  "_build/install/default/lib/Character/character__.cmx"
  "_build/install/default/lib/Character/character__.ml"
  "_build/install/default/lib/Character/character__Infobanks.cmi"
  "_build/install/default/lib/Character/character__Infobanks.cmt"
  "_build/install/default/lib/Character/character__Infobanks.cmx"
  "_build/install/default/lib/Character/dune-package"
  "_build/install/default/lib/Character/infobanks.ml"
  "_build/install/default/lib/Character/opam"
]
libexec: [
  "_build/install/default/lib/Character/character.cmxs"
]
doc: [
  "_build/install/default/doc/Character/README.md"
]
